### ISSUE TITLE
circular deps generated

### ISSUE THREAD

**Issue by Morriz** [omar-dulaimi/prisma-yup-generator#7]
### Bug description

Hi, the generated output circular references blocking bundlers like webpack. It would be very beneficial to solve this so that we can bundle it for web.

### How to reproduce

```
// config.next.js
/* eslint-disable @typescript-eslint/no-var-requires */
const CircularDependencyPlugin = require('circular-dependency-plugin')

module.exports = withTM({
  reactStrictMode: true,
  swcMinify: false,
  future: {
    webpack5: true, // by default, if you customize webpack config, they switch back to version 4.
    // Looks like backward compatibility approach.
  },
  webpack(config) {
    const circularDependencyPlugin = new CircularDependencyPlugin({
      // exclude detection of files based on a RegExp
      exclude: /a\.js|node_modules/,
      // include specific files based on a RegExp
      // include: //,
      // add errors to webpack instead of warnings
      failOnError: true,
      // allow import cycles that include an asyncronous import,
      // e.g. via import(/* webpackMode: "weak" */ './file.js')
      allowAsyncCycles: false,
      // set the current working directory for displaying module paths
      cwd: process.cwd(),
      // `onStart` is called before the cycle detection starts
      onStart({ compilation }) {
        console.log('start detecting webpack modules cycles')
      },
      // `onDetected` is called for each module that is cyclical
      onDetected({ module: webpackModuleRecord, paths, compilation }) {
        console.log('new CD error')
        console.log(paths)
        // `paths` will be an Array of the relative module paths that make up the cycle
        // `module` will be the module record generated by webpack that caused the cycle
        compilation.errors.push(new Error(paths.join(' -> ')))
      },
      // `onEnd` is called before the cycle detection ends
      onEnd({ compilation }) {
        console.log('end detecting webpack modules cycles')
      },
    })
    config.plugins.push(circularDependencyPlugin)
    return config
  },
})
```

### Expected behavior

No circular references to exist. It should be avoidable by following this paradigm that exports everything from one file: https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

### Prisma information

// prisma/schema.prisma

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

generator fieldEncryptionMigrations {
  provider = "prisma-field-encryption"
  output   = "./migrations"
}

generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "../node_modules/.cache/type-graphql"
}

generator yup {
  provider = "prisma-yup-generator"
  output   = "../src/prisma/gen"
}

generator erd {
  provider = "prisma-erd-generator"
  output   = "../docs/diagrams/entity-relationship-diagram.svg"
}

enum Role {
  ADMIN
  USER
}

enum OrgRole {
  OWNER
  ADMIN
  MEMBER
}

enum Tier {
  FREE
  PRO
  ENTERPRISE
}

enum PaymentStatus {
  PENDING
  PAID
}

model License {
  tier        Tier
  price       Int
  description String

  @@unique([tier])
}

enum InvoicePeriod {
  MONTHLY
  YEARLY
}

model Account {
  id                String        @id @default(cuid())
  createdAt         DateTime      @default(now())
  updatedAt         DateTime      @updatedAt
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?       @map("refreshToken") @db.Text
  access_token      String?       @map("accessToken") @db.Text
  expires_at        Int?          @map("expiresAt")
  token_type        String?       @map("tokenType")
  scope             String?
  id_token          String?       @map("idToken") @db.Text
  session_state     String?       @map("sessionState")
  user              User          @relation(fields: [userId], references: [id], onDelete: Cascade)
  tier              Tier          @default(FREE) // may be upgraded to PRO then ENTERPRISE
  clusters          Cluster[]
  organisation      Organisation?
  invoice           Invoice[]

  @@unique([provider, providerAccountId])
}

model Session {
  id            String   @id @default(cuid())
  createdAt     DateTime @default(now())
  updatedAt     DateTime @updatedAt
  userId        String
  expires       DateTime
  session_token String   @unique @map("sessionToken")
  user          User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  phoneNumber   String? /// @encrypted
  address       String? /// @encrypted
  country       String?
  state         String?
  city          String? /// @encrypted
  zipCode       String? /// @encrypted
  avatarUrl     String? /// @encrypted
  company       String?

  role     Role      @default(USER)
  accounts Account[]
  sessions Session[]
  userOrgs UserOrg[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model UserOrg {
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt
  userId         String       @map("user_id")
  organisationId String
  role           OrgRole
  user           User         @relation(fields: [userId], references: [id], onDelete: Cascade)
  organisation   Organisation @relation(fields: [organisationId], references: [id])

  @@id([userId, organisationId])
}

model Invoice {
  id        String        @id @default(uuid())
  createdAt DateTime      @default(now())
  updatedAt DateTime      @updatedAt
  accountId String
  price     Int // no fractions, will be exactly as paid in EURO at that moment in time
  status    PaymentStatus
  period    InvoicePeriod
  startDate DateTime
  endDate   DateTime

  account Account @relation(fields: [accountId], references: [id])
}

model Organisation {
  id        String   @id @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  accountId String   @unique
  name      String   @unique
  image     String?

  account  Account   @relation(fields: [accountId], references: [id])
  orgUsers UserOrg[]
}

model Cluster {
  id          String   @id @default(uuid())
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  key         String   @default(cuid())
  accountId   String
  name        String
  description String
  provider    String
  kubecfg     String?

  account Account @relation(fields: [accountId], references: [id])
}

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 16.14.2

### Prisma Version

```
3.14.0
```

**Comment by omar-dulaimi** [comment]
Hello @Morriz 

I have faced the cyclical dependency issue during development, and made some changes to fix it. So if it's still there, that's weird. 

Could you please prepare a small repo where this issue occurs?
I also need it to test the solution before making the release.

Thank you!

**Comment by Morriz** [comment]
It is not weird as the datamodel creates cross references. So the only solution imo is to make sure that your exports don't. The model I provided should be enough to generate your output. You only have to import one of the objects to use in a nextjs page. BOOM!

**Comment by omar-dulaimi** [comment]
Hopefully I get to fix it by the end of the day.

**Comment by omar-dulaimi** [comment]
Hey @Morriz I'm currently working this bug, and unable to reproduce it.

Please prepare a minimal Nextjs project repo with this issue whenever you can.

**Comment by mubaidr** [comment]
This is happening for me too. Importing schema causes `Error  Maximum call stack size exceeded` error.

**Comment by Morriz** [comment]
I suggest looking at [typegraphql-prisma](https://github.com/MichalLytek/typegraphql-prisma), as it also exports correctly.

**Comment by omar-dulaimi** [comment]
Please open a new issue if you face any problems.

**Comment by brunoti** [comment]
Hey, I am having this right now using the following schema:

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum UserType {
  DOCTOR
  PATIENT
}

model User {
  id                   String    @id() @unique @default(uuid()) @db.Uuid
  numericId            Int       @default(autoincrement()) @map("numeric_id")
  email                String
  name                 String
  gender               String?
  cpf                  String?
  birthDate            DateTime? @map("birth_date")
  password             String
  type                 UserType  @default(DOCTOR) @map("type")
  avatar               String?
  facebookToken        String?   @map("facebook_token")
  passwordResetToken   String?   @map("password_reset_token")
  passwordResetExpires DateTime? @map("password_reset_expires") @db.Timestamptz(6)
  isAdmin              Boolean   @default(false) @map("is_admin")
  isActive             Boolean   @default(false) @map("is_active")
  createdAt            DateTime  @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt            DateTime  @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt            DateTime? @map("deleted_at") @db.Timestamptz(6)

  patientData Patient?      @relation("PatientUserRelation")
  doctorData  Doctor?       @relation("DoctorUserRelation")
  addresses   UserAdress[]
  contacts    UserContact[]

  DoctorPatient DoctorPatient[]
  @@map("users")
}

model UserAdress {
  id         String    @id() @unique @default(uuid()) @db.Uuid
  numericId  Int       @default(autoincrement()) @map("numeric_id")
  userId     String    @db.Uuid
  streetName String    @map("street_name")
  zipCode    String    @map("zip_code")
  district   String
  state      String
  city       String
  number     String
  complement String?
  createdAt  DateTime  @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt  DateTime  @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt  DateTime? @map("deleted_at") @db.Timestamptz(6)
  user       User      @relation(fields: [userId], references: [id])

  @@map("user_adress")
}

model UserContact {
  id        String    @id() @unique @default(uuid()) @db.Uuid
  numericId Int       @default(autoincrement()) @map("numeric_id")
  userId    String    @db.Uuid
  email     String?
  area      String
  phone     String
  createdAt DateTime  @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt DateTime  @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt DateTime? @map("deleted_at") @db.Timestamptz(6)

  user User @relation(fields: [userId], references: [id])

  @@map("users_contacts")
}

model Patient {
  id        String    @id() @unique @default(uuid()) @db.Uuid
  numericId Int       @default(autoincrement()) @map("numeric_id")
  userId    String    @unique @map("user_id") @db.Uuid
  createdAt DateTime  @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt DateTime  @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt DateTime? @map("deleted_at") @db.Timestamptz(6)

  user          User            @relation("PatientUserRelation", fields: [userId], references: [id])
  anamnesis     Anamnesis[]
  evaluations   Evaluation[]    @relation("EvaluationPatientRelation")
  doctorPatient DoctorPatient[]

  @@map("patients")
}

model Doctor {
  id          String    @id() @unique @default(uuid()) @db.Uuid
  numericId   Int       @default(autoincrement()) @map("numeric_id")
  userId      String    @unique @map("user_id") @db.Uuid
  specialtyId String    @map("specialty_id") @db.Uuid
  crfa        String?
  createdAt   DateTime  @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt   DateTime  @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt   DateTime? @map("deleted_at") @db.Timestamptz(6)

  specialty     Specialty       @relation(fields: [specialtyId], references: [id])
  user          User            @relation("DoctorUserRelation", fields: [userId], references: [id])
  anamnesis     Anamnesis[]
  evaluations   Evaluation[]    @relation("EvaluationDoctorRelation")
  doctorPatient DoctorPatient[]
  templates     Template[]

  @@map("doctors")
}

model DoctorPatient {
  doctorId     String   @map("doctor_id") @db.Uuid
  patientId    String   @map("patient_id") @db.Uuid
  assignedById String   @map("created_by") @db.Uuid
  createdAt    DateTime @default(now()) @map("created_at") @db.Timestamptz(6)
  active       Boolean  @default(true) @map("active")

  doctor     Doctor  @relation(fields: [doctorId], references: [id])
  patient    Patient @relation(fields: [patientId], references: [id])
  assignedBy User    @relation(fields: [assignedById], references: [id])

  @@id([doctorId, patientId])
  @@map("doctor_patient")
}

model Specialty {
  id        String   @id() @unique @default(uuid()) @db.Uuid
  numericId Int      @default(autoincrement()) @map("numeric_id")
  name      String
  isActive  Boolean  @default(true) @map("is_active")
  createdAt DateTime @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt DateTime @default(now()) @map("updated_at") @db.Timestamptz(6)

  doctors     Doctor[]
  templates   Template[]
  evaluations Evaluation[]
  anamnesis   Anamnesis[]

  @@map("specialties")
}

model Anamnesis {
  id          String    @id() @unique @default(uuid()) @db.Uuid
  numericId   Int       @default(autoincrement()) @map("numeric_id")
  patientId   String    @map("patient_id") @db.Uuid
  doctorId    String    @map("doctor_id") @db.Uuid
  specialtyId String    @map("specialty_id") @db.Uuid
  questions   Json      @default("[]") @db.Json
  title       String?
  text        String?   @db.Text
  createdAt   DateTime  @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt   DateTime  @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt   DateTime? @map("deleted_at") @db.Timestamptz(6)

  patient   Patient   @relation(fields: [patientId], references: [id])
  doctor    Doctor    @relation(fields: [doctorId], references: [id])
  specialty Specialty @relation(fields: [specialtyId], references: [id])

  @@map("anamnesis")
}

model Evaluation {
  id              String    @id() @unique @default(uuid()) @db.Uuid
  numericId       Int       @default(autoincrement()) @map("numeric_id")
  patientId       String    @map("patient_id") @db.Uuid
  doctorId        String    @map("doctor_id") @db.Uuid
  specialtyId     String    @map("specialty_id") @db.Uuid
  exercises       Json      @default("[]") @db.Json
  text            String?   @db.Text
  title           String?
  appointmentDate DateTime  @default(now()) @map("appointment_date") @db.Timestamptz(6)
  comments        String?
  createdAt       DateTime  @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt       DateTime  @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt       DateTime? @map("deleted_at") @db.Timestamptz(6)

  patient   Patient   @relation(name: "EvaluationPatientRelation", fields: [patientId], references: [id])
  doctor    Doctor    @relation(name: "EvaluationDoctorRelation", fields: [doctorId], references: [id])
  specialty Specialty @relation(fields: [specialtyId], references: [id])

  @@map("evaluations")
}

enum TemplateType {
  ANAMNESIS
  EVALUATION
}

model Template {
  id          String       @id() @unique @default(uuid()) @db.Uuid
  numericId   Int          @default(autoincrement()) @map("numeric_id")
  doctorId    String       @map("doctor_id") @db.Uuid
  type        TemplateType
  specialtyId String       @map("specialty_id") @db.Uuid
  title       String
  html        String       @db.Text
  isActive    Boolean      @default(true) @map("is_active")
  createdAt   DateTime     @default(now()) @map("created_at") @db.Timestamptz(6)
  updatedAt   DateTime     @default(now()) @map("updated_at") @db.Timestamptz(6)
  deletedAt   DateTime?    @map("deleted_at") @db.Timestamptz(6)

  doctor    Doctor    @relation(fields: [doctorId], references: [id])
  specialty Specialty @relation(fields: [specialtyId], references: [id])

  @@map("templates")
}
```

ERROR:


```
/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:119152
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at checkIdentifier (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:72707:28)
    at checkExpressionWorker (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:80858:28)
    at checkExpression (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:80807:38)
    at checkExpressionForMutableLocation (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:80558:24)
    at checkArrayLiteral (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:74346:32)
    at checkExpressionWorker (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:80888:28)
    at checkExpression (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:80807:38)
    at /Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:76213:21
    at Object.forEach (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:377:30)
    at resolveUntypedCall (/Users/bruno/personal/back-fenabb/node_modules/.pnpm/typescript@4.8.2/node_modules/typescript/lib/typescript.js:76212:20)
 ELIFECYCLE  Command failed with exit code 1.
 ```
